runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /static 
  static_dir: static 
  application_readable: true
- url: /.*
  script: main.app

libraries:
- name: flask
  version: 0.12
